# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d29a95a28db4e84a33fcca38d8a2abdc79959eecdb0b78301765413340a291aaa0c7d4e4aaf5f7fdc837b9ce8cb74eef5bc052735c97284f5434b278546c846

test:
  secret_key_base: 1c206b8d450f73b3b1cf117a761a5746861de7db263d61c2dffd4b372355d0491b46ed35cb99c2de4dbc0bab457eacce0bdec5feab4fea1e2b9158a99fe74bd4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
